### ISSUE TITLE
لوگوی جدید بانک رفاه

### ISSUE THREAD

**Issue by hmmftg** [webdesigniran/IranianBankLogos#10]
با سلام
بانک رفاه جدیدا لوگوی خودش رو تغییر داده
[https://www.refah-bank.ir/Upload/Modules/Contents/asset0/JPG/Arm_Bank/logo%201401/rkb-logo.png](url)
ممنون میشیم نسخه جدید رو هم بذارید

**Comment by ghost** [comment]
دسترسی به لینک از طریق اینترنت میسر نشد!
لطفا در صورت امکان اضافه کنید و پول.ریکوئست بزنید تا به شاخه اصلی پروژه اضافه شود. 
متشکرم از اطلاع رسانی.

**Comment by amastaneh** [comment]
ظاهرا [arminamirinasab](https://github.com/arminamirinasab) در حال آپدیت لوگو است و به زودی در شاخه اصلی ادغام میشه.

مرجع: https://github.com/amastaneh/IranianBankLogos/pull/11

**Comment by arminamirinasab** [comment]
تغییرات Merge شد. @hmmftg
