### ISSUE TITLE
لوگوها با فرمت اس‌وی‌جی

### ISSUE THREAD

**Issue by JohnAdib** [webdesigniran/IranianBankLogos#2]
سلام
پیشنهاد میکنم خروجی اس‌وی‌جی لوگوها رو هم قرار بدین تا برای استفاده توی فونت هم مناسب باشه و کیفیت هم کاهش پیدا نکنه

**Comment by JohnAdib** [comment]
هم‌چنین علاوه بر بانک‌ها اگه لوگوی درگاه‌های پرداخت هم میتونه اضافه بشه

**Comment by amastaneh** [comment]
با سلام
تمامی لوگو به صورت غیر برداری (رستر) ارائه شده اند و نسخه اس‌وی‌جی ندارند
باعث خوشحالیه اگه با کمک شما حتی تعداد محدودی از نسخه های اس‌وی‌جی رو فراهم بشه
برای درگاه‌های بانکی هم سعی می کنم به زودی اضافه کنم
با سپاس

**Comment by JohnAdib** [comment]
یه سری مبدل هست که میشه استفاده موقت کرد
ولی برای درگاه‌ها که بیشتر از لوگوی بانک‌ها کاربرد داره میتونین شروع کنید. البته متاسفانه این بعضی از این لوگوها به سختی قابل دسترسی است و خودشون هم ندارن:)

**Comment by asadion** [comment]
سلام لوگو ها را تبدیل به وکتور کنیم و سپس به
SVG
امکان پذیره؟

**Comment by amastaneh** [comment]
&#x202b;از لحاظ فنی امکان پذیر است. لطفا در صورت امکان نتیجه را هم روی مسیر اصلی / master اضافه فرمایید تا به یادگار از شما باقی بمونه.

**Comment by amastaneh** [comment]
یک فولدر برای همین منظور (ذخیره نسخه های svg) به پروژه اضافه شد.
