### ISSUE TITLE
مشکل در بسته های npm

### ISSUE THREAD

**Issue by yeganehaym** [webdesigniran/IranianBankLogos#3]
سلام با تشکر از زحمات شما
از  طریق  
npm
که نصب کردم متاسفانه کار نکرد و فقط فضای لوگو رو گرفت.
مجبور شدم از داخل مخزن دانلود کنم

**Comment by amastaneh** [comment]
با سلام
حتما در اولین فرصت، مجدد بررسی و رفع ایراد می شود.
لطفا اگر راهکاری برای این مشکل به ذهن شما می رسد در پاسخ ارسال فرمایید.
باسپاس

**Comment by yeganehaym** [comment]
فایل های روی مخزن صحیح هستند
این فایل های باید جایگزین نسخه موجود در 
npm
شوند

**Comment by mrmashal** [comment]
سلام
ظاهرا هنوز پکیج
npm
مشکل داره و آفست‌های بک‌گراند توی فایلهایی که گرفته میشه مثبت هست

به نظرم اگر فرصت نمیکنید حداقل دستورالعملش رو از
README
حذف کنید ملت مثل ما سردرگم نشن😊

**Comment by amastaneh** [comment]
نسخه جدید npm منتشر شد
یک دمو مبتنی بر react با توجه به نسخه جدید npm ساخته و منتشر شد
