### ISSUE TITLE
بانک کشاورزی

### ISSUE THREAD

**Issue by SajjadKharrazi** [webdesigniran/IranianBankLogos#4]
لوگوی بانک کشاوزی هم تصحیح کنید عالی میشه

**Comment by amastaneh** [comment]
<div dir='rtl' align='right'>سجاد جان از دقت نظر شما سپاسگزارم.</div>
<div dir='rtl' align='right'>شما می توانید کل پروژه را Fork کرده و بعد از انجام تغییرات مناسب Pull requests فرمایید. لطفا در این زمینه به هر طریقی همکاری فرمایید.</div>

**Comment by amastaneh** [comment]
متاسفانه نسخه باکیفیت از لوگوی این بانک را پیدا کردم.
لطفا در صورت مشاهده نسخه وکتور یا با کیفیت بالا همینجا به اشتراک بگذارید یا Pull requests بزنید.
